<?php $_boxes = $this->getBoxes() ?>
<?php $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>
<?php $_i = 1 ?>
<?php if (count($_boxes)) : ?>
<div class="hp-boxes">
    <?php foreach ($_boxes as $_box) : ?>
        <div class="hp-box column_<?php echo $_i ?>">
            <?php if (!empty($_box['link'])) : ?>
            <a href="<?php echo $this->getUrl($_box['link']) ?>">
                <?php endif ?>
                <img src="<?php echo $media_url.DS.'theme'.DS.$_box['image'] ?>"/>
        <?php if (!empty($_box['link'])) : ?>
            </a>
            <?php endif ?>
        </div>
        <?php if ($_i === 3) { $_i = 1; } else { $_i++; } ?>
    <?php endforeach ?>
</div>
<?php endif ?>