
<div class="block block-subscribe homepage-newsletter">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-homepage">
                <span class="newsletter-text"><?php echo $this->__('Sign up to our emails for the chance to win &pound;200 to spend at '.Mage::getStoreConfig('general/store_information/name')) ?></span>
            <div class="input-box">
                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter-home" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-homepage');
        //]]>
    </script>
</div>
